### ISSUE TITLE
pre-install PHP

### ISSUE THREAD

**Issue by dag-io** [bitrise-io/osx-box-bootstrap#12]
I use PHP 5.6 in some steps. 
Having it already installed would speed up the workflow. 
Lately installing php was slower than usually.

```
INFO[12:51:02] (homebrew/php/php56) isn't installed, installing... 
INFO[13:03:37]  * [OK] homebrew/php/php56 installed 
INFO[13:03:37]  * [OK] Step dependency (homebrew/php/php56) installed, available. 
```

**Comment by viktorbenei** [comment]
Hi,

We discussed about this and we're not sure..

Installing a `brew` package is OK, although we try not to modify the tool versions which come with OS X by default as most users will use that version for ad-hock scripting etc.

In your case: why do you need a specific PHP version? The issue is, Homebrew versions explicitely states that a versioned formula might disappear any time, it's supported as long as there's enough demand or something like that.

So, `brew install php` would be fine, but installing a brew version formula.. We're not sure about it.

**Comment by dag-io** [comment]
Hey

I don't need a specific version. I mean the 5.6 or the 7.0 (last stable) is fine.

OS X : Ok I can try the default one. In that case i will remove the dependency in the step config.

Linux : Is PHP pre-installed ?

**Comment by viktorbenei** [comment]
> Linux : Is PHP pre-installed ?

Did you try `php --version` ? ;)
